# Generated by Django 3.2 on 2023-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230317_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_mane',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
