# Generated by Django 3.2 on 2023-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230317_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг произведения'),
            preserve_default=False,
        ),
    ]
