# Generated by Django 3.2 on 2023-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230317_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг произведения'),
        ),
    ]
