# Generated by Django 3.2 on 2023-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание произведения'),
        ),
    ]
