# Generated by Django 3.2 on 2023-03-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_title_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='text',
            new_name='description',
        ),
    ]
